services:
  nginx:
    ports:
      - "80:80"
    volumes:
      - ./nginx.dev.conf:/etc/nginx/conf.d/default.conf:ro
    command: nginx -g "daemon off;"

  certbot:
    entrypoint: "/bin/sh -c 'exit 0'"
